src/Entity/Personne.php
<?php

namespace App\Entity;

use App\Repository\PersonneRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\InheritanceType;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;


/**
 * @ORM\Entity(repositoryClass=PersonneRepository::class)
 */
class Personne implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    protected $nom;

    /**
     * @ORM\Column(type="string", length=100)
     */
    protected $prenom;

    /**
     * @ORM\Column(type="integer")
     */
    protected $telephone;

    /**
     * @ORM\Column(type="string", length=100)
     */
    protected $nom_utilisateur;

    /**
     * @ORM\Column(type="string", length=100)
     */
    protected $mot_de_passe;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getTelephone(): ?int
    {
        return $this->telephone;
    }

    public function setTelephone(int $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getNomUtilisateur(): ?string
    {
        return $this->nom_utilisateur;
    }

    public function setNomUtilisateur(string $nom_utilisateur): self
    {
        $this->nom_utilisateur = $nom_utilisateur;

        return $this;
    }

    public function getMotDePasse(): ?string
    {
        return $this->mot_de_passe;
    }

    public function setMotDePasse(string $mot_de_passe): self
    {
        $this->mot_de_passe = $mot_de_passe;

        return $this;
    }

    public function __toString() {
        return $this->nom;
    }

    private $email;

 

    /**
     * @var string The hashed password
     */
    private $password;

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->nom_utilisateur;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

src/Entity/Voiture.php
<?php

namespace App\Entity;

use App\Repository\VoitureRepository;
 use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=VoitureRepository::class)
 */
class Voiture
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $marque;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $modele;

    /**
     * @ORM\Column(type="integer")
     */
    private $numero_identifiant;

    /**
     * @ORM\Column(type="integer")
     */
    private $numero_serie;

    /**
     * @ORM\Column(type="date")
     */     
    private $date_achat;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $couleur;

    /**
     * @ORM\OneToOne(targetEntity=Vente::class, mappedBy="voiture", cascade={"persist", "remove"})
     */
    private $vente;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(string $marque): self
    {
        $this->marque = $marque;

        return $this;
    }

    public function getModele(): ?string
    {
        return $this->modele;
    }

    public function setModele(string $modele): self
    {
        $this->modele = $modele;

        return $this;
    }

    public function getNumeroIdentifiant(): ?int
    {
        return $this->numero_identifiant;
    }

    public function setNumeroIdentifiant(int $numero_identifiant): self
    {
        $this->numero_identifiant = $numero_identifiant;

        return $this;
    }

    public function getNumeroSerie(): ?int
    {
        return $this->numero_serie;
    }

    public function setNumeroSerie(int $numero_serie): self
    {
        $this->numero_serie = $numero_serie;

        return $this;
    }

    public function getDateAchat(): ?\DateTimeInterface
    {
        return $this->date_achat;
    }

    public function setDateAchat(\DateTimeInterface $date_achat): self
    {
        $this->date_achat = $date_achat;

        return $this;
    }

    public function getCouleur(): ?string
    {
        return $this->couleur;
    }

    public function setCouleur(string $couleur): self
    {
        $this->couleur = $couleur;

        return $this;
    }

    public function getVente(): ?Vente
    {
        return $this->vente;
    }

    public function setVente(Vente $vente): self
    {
        // set the owning side of the relation if necessary
        if ($vente->getVoiture() !== $this) {
            $vente->setVoiture($this);
        }

        $this->vente = $vente;

        return $this;
    }

    public function __toString(){
        return $this->numero_serie;
    }
}

src/Controller/TableauDeBordController.php
<?php

namespace App\Controller;

use App\Repository\VoitureRepository;
use App\Repository\ClientRepository;
use App\Repository\VenteRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class TableauDeBordController extends AbstractController
{
    /** 
     *  @Route("/tableau_de_bord", name="app_tableau_de_bord")
     */
    public function allVoiture(VoitureRepository $voitureRepository,ClientRepository $clientRepository,VenteRepository $venteRepository,RequestStack $requestStack ): Response
    {
        $voitures=$voitureRepository->findAll();
        $clients=$clientRepository->findAll();
        $ventes=$venteRepository->findAll();

        $session = $requestStack->getSession();
        $username=$session->get('nomUtilisateur');
        $nom=$session->get('nom');
        $prenom=$session->get('prenom');
        // if ($username==null) {
        //     return $this->redirectToRoute("authentification");
        // }

        return $this->render('tableau_de_bord/index.html.twig', [
            'nombre_voiture' => count($voitures),
            'nombre_client' => count($clients),
            'nombre_vente' => count($ventes),
            'nom' => $nom,
            'prenom' => $prenom,
            'username' => $username,

        ]);
    }

    /** 
      * @Route("/Voiture",name="Voiture")
      */

    public function Voiture(VoitureRepository $voitureRepository )
    { 
        

      $numero = $_GET['marque'];
 


      return $this->render('tableau_de_bord/searchVoiture.html.twig',array(

        
        
      'voitures'=>$voitureRepository->searchVoiture($numero)));
    
    }

     /** 
      * @Route("/Client",name="Client")
      */

      public function Client(ClientRepository $clientRepository )
      { 
          
  
        $search = $_GET['cni'];
   
  
  
        return $this->render('tableau_de_bord/ClientSearch.html.twig',array(
  
          
          
        'clients'=>$clientRepository->ClientSearch($search)));
      
      }

   
}

templates/tableau_de_bord/ClientSearch.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {% block contenu %}
            <div class="row">
        <div class="col-12">
            <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                <h6 class="text-white text-capitalize ps-3">Clients</h6>
                <div class="col-6 text-end">
                </div>
            </div>
            
            <div class="card-body px-0 pb-2">
            
                <div class="table-responsive p-0">
                <a class="btn bg-gradient-dark mb-0" href="{{ path('app_client_ajout') }}"><i class="material-icons text-sm">add</i>&nbsp;&nbsp;Ajouter un Client</a>
                <table class="table align-items-center mb-0">
                    <thead>
                        <tr>
                            <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">id</th>
                            <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Cni</th>
                            <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Nom</th>
                            <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Prenom</th>
                            <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Telephone</th>
                            <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Nom de l'utilisateur</th>
                            <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Mot de passe</th>
                            <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Actions</th>
                            <th class="text-secondary opacity-7"></th>
                        </tr>
                    </thead>
                   
                {% for client in clients %}
                    <tr>
                        <td>
                            <div class="d-flex px-2 py-1">
                                {{ client.id }}    
                            </div>
                        </td>

                        <td>
                                {{ client.cni }} 
                        </td>

                        <td class="align-middle text-center text-sm">
                                {{ client.nom }} 
                        </td>

                        <td class="align-middle text-center">
                                {{ client.prenom }}
                        </td>

                        <td class="align-middle text-center">
                                {{ client.telephone }}
                        </td>

                        <td class="align-middle">
                                {{ client.nomUtilisateur }}
                        </td>

                        <td class="align-middle">
                                {{ client.motDePasse }} 
                        </td>

                        <td>
                            <div class="d-flex px-2 py-1">
                                <div class="ms-auto text-end">
                                    <a class="btn btn-link text-danger text-gradient px-3 mb-0" href="{{ path('app_supprimer_client', {'id': client.id}) }}"><i class="material-icons text-sm me-2">delete</i>Delete</a>
                                    <a class="btn btn-link text-dark px-3 mb-0" href="{{ path('app_modifier_client', {'id': client.id}) }}"><i class="material-icons text-sm me-2">edit</i>Edit</a>
                                </div>
                            </div>
                        </td>
                    </tr>
                  </tbody>
                {% endfor %}  
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    {% endblock %} 
{% endblock %}

templates/tableau_de_bord/index.html.twig
{% extends 'base.html.twig' %}


{% block gestion_page %}Tableau de Bord{% endblock %}
{% block page_courante %}{% endblock %}


{% block contenu %}
   <div class="row">
        <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
          <div class="card">
            <div class="card-header p-3 pt-2">
              <div class="icon icon-lg icon-shape bg-gradient-dark shadow-dark text-center border-radius-xl mt-n4 position-absolute">
                <i class="material-icons opacity-10">airport_shuttle</i>
              </div>
              <div class="text-end pt-1">
                <p class="text-sm mb-0 text-capitalize">Nombre Voiture</p>
                <h4 class="mb-0">{{nombre_voiture}}</h4>
              </div>
            </div>
            <hr class="dark horizontal my-0">
            <div class="card-footer p-3">
              <p class="mb-0"><span class="text-success text-sm font-weight-bolder">+5% </span>cette semaine</p>
            </div>
          </div>
        </div>
        <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
          <div class="card">
            <div class="card-header p-3 pt-2">
              <div class="icon icon-lg icon-shape bg-gradient-success shadow-success text-center border-radius-xl mt-n4 position-absolute">
                <i class="material-icons opacity-10">person</i>
              </div>
              <div class="text-end pt-1">
                <p class="text-sm mb-0 text-capitalize">Nombre Client</p>
                <h4 class="mb-0">{{nombre_client}}</h4>
              </div>
            </div>
            <hr class="dark horizontal my-0">
            <div class="card-footer p-3">
              <p class="mb-0"><span class="text-danger text-sm font-weight-bolder">2%</span>cette semaine</p>
            </div>
          </div>
        </div>
        <div class="col-xl-3 col-sm-6">
          <div class="card">
            <div class="card-header p-3 pt-2">
              <div class="icon icon-lg icon-shape bg-gradient-info shadow-info text-center border-radius-xl mt-n4 position-absolute">
                <i class="material-icons opacity-10">monetization_on</i>
              </div>
              <div class="text-end pt-1">
                <p class="text-sm mb-0 text-capitalize">Nombre Vente</p>
                <h4 class="mb-0">0</h4>
              </div>
            </div>
            <hr class="dark horizontal my-0">
            <div class="card-footer p-3">
              <p class="mb-0"><span class="text-success text-sm font-weight-bolder">0% </span>pour le moment</p>
            </div>
          </div>
        </div>
      </div>

{% endblock %}

templates/tableau_de_bord/search.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	
    {% block contenu %}
          <div class="row">
        <div class="col-12">
          <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                <h6 class="text-white text-capitalize ps-3">Voitures</h6>
                <div class="col-6 text-end"></div>
              </div>
            </div>
            <div class="card-body px-0 pb-2">
              <div class="table-responsive p-0">
               <a class="btn bg-gradient-dark mb-0" href="{{ path('app_voiture_new') }}"><i class="material-icons text-sm">add</i>&nbsp;&nbsp;Ajouter une Voiture</a>
                <table class="table align-items-center mb-0">
                  <thead>
                    <tr>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">id</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">marque</th>
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">modele</th>
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">numero d'identifiant</th>
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">numero de serie</th>
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">date d'achat</th>
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">couleur</th>
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Actions</th>
                      <th class="text-secondary opacity-7"></th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for voiture in voitures %}
                    <tr>
                      <td>
                        <div class="d-flex px-2 py-1">
                         {{ voiture.id }}    
                        </div>
                      </td>
                      <td>
                        {{ voiture.marque }} 
                       
                      </td>
                      <td class="align-middle text-center text-sm">
                       {{ voiture.modele }} 
                      </td>
                      <td class="align-middle text-center">
                       {{ voiture.numeroIdentifiant }}
                      </td>
                      <td class="align-middle text-center">
                      {{ voiture.numeroSerie }}
                      </td>
                      <td class="align-middle">
                       {{ voiture.dateAchat ? voiture.dateAchat|date('Y-m-d') : '' }}
                      </td>

                      <td class="align-middle">
                       {{ voiture.couleur }} 
                      </td>

                       <td>
                        <div class="d-flex px-2 py-1">
                         <div class="ms-auto text-end">
                          {# {{ include('voiture/_delete_form.html.twig') }} #}
                             <a class="btn btn-link text-danger text-gradient px-3 mb-0" href="{{ path('app_voiture_delete', {'id': voiture.id}) }}"><i class="material-icons text-sm me-2">delete</i>Delete</a>
                             <a class="btn btn-link text-dark px-3 mb-0" href="{{ path('app_voiture_edit', {'id': voiture.id}) }}"><i class="material-icons text-sm me-2">edit</i>Edit</a>
                            </div>
                        </div>
                      </td>

                    </tr>

                  </tbody>
                {% endfor %}  
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    {% endblock %} 
{% endblock %}

templates/tableau_de_bord/searchVoiture.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	
    {% block contenu %}
          <div class="row">
        <div class="col-12">
          <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                <h6 class="text-white text-capitalize ps-3">Voitures</h6>
                <div class="col-6 text-end"></div>
              </div>
            </div>
            <div class="card-body px-0 pb-2">
              <div class="table-responsive p-0">
               <a class="btn bg-gradient-dark mb-0" href="{{ path('app_voiture_new') }}"><i class="material-icons text-sm">add</i>&nbsp;&nbsp;Ajouter une Voiture</a>
                <table class="table align-items-center mb-0">
                  <thead>
                    <tr>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">id</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">marque</th>
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">modele</th>
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">numero d'identifiant</th>
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">numero de serie</th>
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">date d'achat</th>
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">couleur</th>
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Actions</th>
                      <th class="text-secondary opacity-7"></th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for voiture in voitures %}
                    <tr>
                      <td>
                        <div class="d-flex px-2 py-1">
                         {{ voiture.id }}    
                        </div>
                      </td>
                      <td>
                        {{ voiture.marque }} 
                       
                      </td>
                      <td class="align-middle text-center text-sm">
                       {{ voiture.modele }} 
                      </td>
                      <td class="align-middle text-center">
                       {{ voiture.numeroIdentifiant }}
                      </td>
                      <td class="align-middle text-center">
                      {{ voiture.numeroSerie }}
                      </td>
                      <td class="align-middle">
                       {{ voiture.dateAchat ? voiture.dateAchat|date('Y-m-d') : '' }}
                      </td>

                      <td class="align-middle">
                       {{ voiture.couleur }} 
                      </td>

                       <td>
                        <div class="d-flex px-2 py-1">
                         <div class="ms-auto text-end">
                          {# {{ include('voiture/_delete_form.html.twig') }} #}
                             <a class="btn btn-link text-danger text-gradient px-3 mb-0" href="{{ path('app_voiture_delete', {'id': voiture.id}) }}"><i class="material-icons text-sm me-2">delete</i>Delete</a>
                             <a class="btn btn-link text-dark px-3 mb-0" href="{{ path('app_voiture_edit', {'id': voiture.id}) }}"><i class="material-icons text-sm me-2">edit</i>Edit</a>
                            </div>
                        </div>
                      </td>

                    </tr>

                  </tbody>
                {% endfor %}  
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    {% endblock %} 
{% endblock %}