src/Entity/Vente.php
<?php

namespace App\Entity;

use App\Repository\VenteRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=VenteRepository::class)
 */
class Vente
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date_vente;

    /**
     * @ORM\Column(type="integer")
     */
    private $montant;

    /**
     * @ORM\OneToOne(targetEntity=Voiture::class, inversedBy="vente", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $voiture;

    /**
     * @ORM\ManyToOne(targetEntity=Client::class, inversedBy="ventes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $client;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateVente(): ?\DateTimeInterface
    {
        return $this->date_vente;
    }

    public function setDateVente(\DateTimeInterface $date_vente): self
    {
        $this->date_vente = $date_vente;

        return $this;
    }

    public function getMontant(): ?int
    {
        return $this->montant;
    }

    public function setMontant(int $montant): self
    {
        $this->montant = $montant;

        return $this;
    }

    public function getVoiture(): ?Voiture
    {
        return $this->voiture;
    }

    public function setVoiture(Voiture $voiture): self
    {
        $this->voiture = $voiture;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }
}

src/Entity/Voiture.php
<?php

namespace App\Entity;

use App\Repository\VoitureRepository;
 use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=VoitureRepository::class)
 */
class Voiture
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $marque;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $modele;

    /**
     * @ORM\Column(type="integer")
     */
    private $numero_identifiant;

    /**
     * @ORM\Column(type="integer")
     */
    private $numero_serie;

    /**
     * @ORM\Column(type="date")
     */     
    private $date_achat;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $couleur;

    /**
     * @ORM\OneToOne(targetEntity=Vente::class, mappedBy="voiture", cascade={"persist", "remove"})
     */
    private $vente;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(string $marque): self
    {
        $this->marque = $marque;

        return $this;
    }

    public function getModele(): ?string
    {
        return $this->modele;
    }

    public function setModele(string $modele): self
    {
        $this->modele = $modele;

        return $this;
    }

    public function getNumeroIdentifiant(): ?int
    {
        return $this->numero_identifiant;
    }

    public function setNumeroIdentifiant(int $numero_identifiant): self
    {
        $this->numero_identifiant = $numero_identifiant;

        return $this;
    }

    public function getNumeroSerie(): ?int
    {
        return $this->numero_serie;
    }

    public function setNumeroSerie(int $numero_serie): self
    {
        $this->numero_serie = $numero_serie;

        return $this;
    }

    public function getDateAchat(): ?\DateTimeInterface
    {
        return $this->date_achat;
    }

    public function setDateAchat(\DateTimeInterface $date_achat): self
    {
        $this->date_achat = $date_achat;

        return $this;
    }

    public function getCouleur(): ?string
    {
        return $this->couleur;
    }

    public function setCouleur(string $couleur): self
    {
        $this->couleur = $couleur;

        return $this;
    }

    public function getVente(): ?Vente
    {
        return $this->vente;
    }

    public function setVente(Vente $vente): self
    {
        // set the owning side of the relation if necessary
        if ($vente->getVoiture() !== $this) {
            $vente->setVoiture($this);
        }

        $this->vente = $vente;

        return $this;
    }

    public function __toString(){
        return $this->numero_serie;
    }
}

src/Form/VenteType.php
<?php

namespace App\Form;

use App\Entity\Vente;
use App\Entity\Voiture;
use App\Entity\Client;
use App\Repository\VoitureRepository;

use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\DateType;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class VenteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date_vente',DateType::class , [ "attr" => ["class" => "form-control"] ])
            ->add('montant',NumberType::class , [ "attr" => ["class" => "form-control"] ])
            ->add('voiture',EntityType::class,[
                'class' => Voiture::class,
                'choice_label' => 'numeroSerie',
            //     'query_builder' =>function (VoitureRepository $voitureRepository) {
            //     return $voitureRepository->createQueryBuilder('v')
            //     ->andWhere('v.dejaVendue = :val')
            //     ->setParameter('val', false);
            // },
            ])
            ->add('client',EntityType::class,[
                'class' => Client::class,
                'choice_label' => 'nom',
             
            ])
        ;   
        
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Vente::class,
        ]);
    }
}

src/Controller/VenteController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\VenteRepository;
use App\Entity\Vente;
use App\Form\VenteType;

/**
 * @Route("/vente")
 */
class VenteController extends AbstractController
{
    /**
     * @Route("/")
     */
    public function index(): Response
    {
        return $this->render('vente/index.html.twig', [
            'controller_name' => 'VenteController',
        ]);
    }

    /**
     * @Route("/vente/ajout_vente", name="app_ajout_vente")
     */
    public function ajout_vente(Request $request,  EntityManagerInterface $entityManager): Response
    {
        $vente = new vente();
        $form = $this->createForm(VenteType::class, $vente);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($vente);
            // $voitureVendue=$form->getData()->getVoiture();
            // $voitureVendue->setDejaVendue(true);
            $entityManager->flush();
            return $this->redirectToRoute('app_list_vente');
        }

        return $this->renderForm('vente/ajout_vente.html.twig', [
            'vente' => $vente,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/vente/list_vente", name="app_list_vente")
     */
    public function list_client(VenteRepository $venteRepository) {
        $vente = $venteRepository->findAll();
        return $this->render('vente/list_vente.html.twig', array(
            'ventes' =>$vente,
        ));
    }

    /**
     * @Route("/vente/{id}/modifier", name="app_modifier_vente")
     */
    public function modifier_vente(Request $request, Vente $vente, VenteRepository $venteRepository): Response
    {
        $form = $this->createForm(VenteType::class, $vente);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $venteRepository->add($vente);
            return $this->redirectToRoute('app_list_vente');
        }

        return $this->renderForm('vente/modifier_vente.html.twig', [
            'vente' => $vente,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/supprimer_vente/{id}", name="app_supprimer_vente")
     */
    public function supprimer_vente( Vente $vente,EntityManagerInterface $entityManager): Response
    {
        $entityManager ->remove($vente);
        $entityManager ->flush();

        return $this->redirectToRoute('app_list_vente');

    }
   /**
     * @Route("/vente/{id}", name="app_afficher_vente")
     */
    public function afficher_vente(VenteRepository $venteRepository, $id): Response
    {
        $vente=$venteRepository->findOneBy(['id'=>$id]);
        return $this->render('vente/afficher_vente.html.twig', [
            'vente' => $vente,
        ]);
    }
}

templates/vente/_form.html.twig
    {{form_start(form) }}
        <div class="input-group input-group-outline mb-3">
            <label class="form-label">Date Vente</label>
            {{form_widget (form.date_vente) }}
        </div>
        <div class="input-group input-group-outline mb-3">
            <label class="form-label">Montant</label>
            {{form_widget (form.montant) }}
        </div>
        <div class="input-group input-group-outline mb-3">
            <label class="form-label">Voiture</label>
                {{form_widget (form.voiture) }}
        </div>
            <div class="input-group input-group-outline mb-3">
            <label class="form-label">Client</label>
                {{form_widget (form.client) }}
        </div>
                    
        <div class="text-center">
            <input type="submit" class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0" value="{{ button_label|default('Save') }}">
        </div>
    {{ form_end(form)}}

templates/vente/afficher_vente.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {% block gestion_page %}ventes{% endblock %}
    {% block page_courante %}Afficher une vente{% endblock %}

    {% block contenu %}
   
      
        <div class="row">
        
        <div class="col-12">
        
            <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                <h6 class="text-white text-capitalize ps-3">Clients</h6>
                <div class="col-6 text-end">
                </div>
            </div>
            
            <div class="card-body px-0 pb-2">
           
                <div class="table-responsive p-0">
                
                <a class="btn bg-gradient-dark mb-0" href="{{ path('app_ajout_vente') }}"><i class="material-icons text-sm">add</i>&nbsp;&nbsp;Ajouter un Client</a>
                <table class="table align-items-center mb-0">
                    <thead>
                        <tr>
                            <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">id</th>
                            <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Cni</th>
                            <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Nom</th>
                            <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Prenom</th>
                            <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Telephone</th>
                            <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Nom de l'utilisateur</th>
                            <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Mot de passe</th>
                            <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Actions</th>
                            <th class="text-secondary opacity-7"></th>
                        </tr>
                    </thead>
                    
                    <tr>
                        <td>
                            <div class="d-flex px-2 py-1">
                                {{ vente.id }}    
                            </div>
                        </td>

                        <td>
                                {{ vente.dateVente ? vente.dateVente|date('Y-m-d') : ''  }} 
                        </td>

                        <td class="align-middle text-center text-sm">
                                {{ vente.montant }} 
                        </td>

                        <td class="align-middle text-center">
                                {{ vente.client }}
                        </td>

                        <td class="align-middle text-center">
                                {{ vente.voiture }}
                        </td>

                      
                        <td>
                            <div class="d-flex px-2 py-1">
                                <div class="ms-auto text-end">
                                    <a class="btn btn-link text-dark px-3 mb-0" href="{{ path('app_modifier_vente', {'id': vente.id}) }}"><i class="material-icons text-sm me-2">edit</i>MODIFIER</a>
                                    <a class="btn btn-link text-danger text-gradient px-3 mb-0" href="{{ path('app_supprimer_vente', {'id': vente.id}) }}"><i class="material-icons text-sm me-2">delete</i>SUPPRIMER</a>
                                    
                                </div>
                            </div>
                        </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    {% endblock %} 
{% endblock %}

templates/vente/ajout_vente.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une voiture{% endblock %}

{% block body %}
{{ include('voiture/_form.html.twig') }}

    <a href="{{ path('app_list_vente') }}">back to list</a>
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

    {% block contenu %}

        <breadcrumb>

        <div class="card-body">
            {{form_start(form) }}
            <div class="input-group input-group-outline mb-3">
                <label class="form-label">Date Vente</label>
                {{form_widget (form.date_vente) }}
            </div>
            <div class="input-group input-group-outline mb-3">
                <label class="form-label">Montant</label>
                {{form_widget (form.montant) }}
            </div>
            <div class="input-group input-group-outline mb-3">
                <label class="form-label"></label>
                    {{form_widget (form.voiture) }}
            </div>
                <div class="input-group input-group-outline mb-3">
                <label class="form-label"></label>
                    {{form_widget (form.client) }}
            </div>
                        
            <div class="text-center">
                <input type="submit" class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0" value="Enregistrer">
            </div>
            {{ form_end(form)}}
        </div>

    {% endblock %}
{% endblock %}

templates/vente/list_vente.html.twig
{% extends 'base.html.twig' %}

{% block body %}

  
    {% block gestion_page %}Ventes{% endblock %}
    {% block page_courante %}Listes des Ventes{% endblock %}

    {% block contenu %}
    
        
        <div class="row">
            <div class="col-12">
                <div class="card my-4">
                <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                    <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                    <h6 class="text-white text-capitalize ps-3">Ventes</h6>
                    <div class="col-6 text-end">
                    </div>
                </div>
                
                <div class="card-body px-0 pb-2">
                
                    <div class="table-responsive p-0">
                    <a class="btn bg-gradient-dark mb-0" href="{{ path('app_ajout_vente') }}"><i class="material-icons text-sm">add</i>&nbsp;&nbsp;Ajouter une Vente</a>
                    <table class="table align-items-center mb-0">
                        <thead>
                            <tr>
                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">#</th>
                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Date de Vente</th>
                                <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Montant</th>
                                <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Voiture</th>
                                <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Client</th>
                                <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">date d'achat</th>
                                <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Actions</th>
                                <th class="text-secondary opacity-7"></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if ventes == [] %}

                                <tr>
                                    <td>
                                        <div class="d-flex px-2 py-1">
                                        <div class="d-flex flex-column justify-content-center">
                                            <h6 class="mb-0 text-sm">Pas de vente enregistrer </h6>
                                        </div>
                                        </div>
                                    </td>

                                <tr>
                            {% else %}
                            {% for vente in ventes %}
                            <tr>
                                <td>
                                    <div class="d-flex px-2 py-1">
                                        {{ loop.index }}    
                                    </div>
                                </td>

                                <td>
                                {{ vente.dateVente ? vente.dateVente|date('Y-m-d') : '' }}
                                </td>

                                <td class="align-middle text-center text-sm">
                                    {{ vente.montant }} 
                                </td>

                                <td class="align-middle text-center">
                                    {{ vente.voiture }}
                                </td>

                                <td class="align-middle text-center">
                                    {{ vente.client }}
                                </td>

                                <td class="align-middle">
                                    {{ voiture.dateAchat ? voiture.dateAchat|date('Y-m-d') : '' }}
                                </td>

                                <td class="align-middle">
                                    {{ voiture.couleur }} 
                                </td>

                                <td>
                                    <div class="d-flex px-2 py-1">
                                        <div class="ms-auto text-end">
                                            <a class="btn btn-link text-dark px-3 mb-0" href="{{ path('app_modifier_vente', {'id': vente.id}) }}"><i class="material-icons text-sm me-2">edit</i>MODIFIER</a>
                                            <a class="btn btn-link text-danger btn-sm mb-0" data-bs-toggle="modal" data-bs-target="#exampleModal"><i class="material-icons text-sm me-2">delete</i>Supprimer</a>
                                            <!-- Modal -->
                                            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                                <div class="modal-dialog">
                                                    <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="exampleModalLabel">Suppression client</h5>
                                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                    </div>
                                                    <div class="modal-body">
                                                        Etes vous sur de vouloir supprimer cet élément? </br>
                                                        Cette action est irréversible!
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                                        <a href="{{url('app_supprimer_vente', {'id': vente.id})}}"><button type="button" class="btn btn-primary">Supprimer</button></a>
                                                    </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %} 

                            {% endif %} 
                            
                        </tbody>
                    </table>
                </div>
                </div>
            </div>
            </div>
        </div>
        {% endblock %} 
{% endblock %}

templates/vente/modifier_vente.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Vente{% endblock %}

{% block body %}
    <h1>Modifier une vente</h1>

    {{ include('vente/_form.html.twig', {'button_label': 'Update'}) }}

    {% block contenu %}

        <breadcrumb>

        <div class="card-body">
            {{form_start(form) }}
            <div class="input-group input-group-outline mb-3">
                <label class="form-label">Date Vente</label>
                {{form_widget (form.date_vente) }}
            </div>
            <div class="input-group input-group-outline mb-3">
                <label class="form-label">Montant</label>
                {{form_widget (form.montant) }}
            </div>
            <div class="input-group input-group-outline mb-3">
                <label class="form-label">Voiture</label>
                    {{form_widget (form.voiture) }}
            </div>
                <div class="input-group input-group-outline mb-3">
                <label class="form-label">Client</label>
                    {{form_widget (form.client) }}
            </div>
                        
            <div class="text-center">
                <input type="submit" class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0" value="Enregistrer">
            </div>
            {{ form_end(form)}}
        </div>

    {% endblock %}


{% endblock %}

templates/vente/rechercher_vente.html.twig
{% extends 'base.html.twig' %}

{% block titre %} Ventes {% endblock %}

{% block gestion_page %}Ventes {% endblock %}

{% block page_courante %}Résultat de la recherche {% endblock %}

{% block contenu %}

  
 <div class="row">

        <div>
           <a class="btn btn-outline-primary btn-sm mb-4" href="{{url('ventes')}}"><i class="material-icons text-sm me-2">keyboard_return</i>Retour</a>
       </div>
               
       <div class="col-12">
         <div class="card my-4">
           <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
             <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
               <h6 class="text-white text-capitalize ps-3">Liste des Ventes</h6>
             </div>
           </div>
           <div class="card-body px-0 pb-2">
             <div class="table-responsive p-0">
               <table class="table align-items-center mb-0">
                 <thead>
                   <tr>
                     <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">#</th>
                     <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Date Vente</th>
                     <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Montant</th>
                     <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Client</th>
                     <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Voiture</th>
                     <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Actions</th>
                   </tr>
                 </thead>
                 <tbody>
                 {% if ventes == [] %}

                   <tr>
                     <td>
                       <div class="d-flex px-2 py-1">
                         <div class="d-flex flex-column justify-content-center">
                           <h6 class="mb-0 text-sm">Pas de resultat pour la recherche éffectuée.</h6>
                         </div>
                       </div>
                     </td>

                   <tr>

                 {% else %}
                 {% for vente in ventes %}
                     
                 
                   <tr>
                     <td>
                       <div class="d-flex px-2 py-1">
                         <div class="d-flex flex-column justify-content-center">
                           <h6 class="mb-0 text-sm">{{loop.index}}</h6>
                         </div>
                       </div>
                     </td>

                     <td>
                       <div class="d-flex px-2 py-1">
                         <div class="d-flex flex-column justify-content-center">
                           <h6 class="mb-0 text-sm">{{vente.dateVente.format('d/m/Y')}}</h6>
                         </div>
                       </div>
                     </td>

                     <td>
                       <div class="d-flex px-2 py-1">
                         <div class="d-flex flex-column justify-content-center">
                           <h6 class="mb-0 text-sm">{{vente.montant}}</h6>
                         </div>
                       </div>
                     </td>

                     <td>
                       <div class="d-flex px-2 py-1">
                         <div class="d-flex flex-column justify-content-center">
                           <h6 class="mb-0 text-sm">{{vente.client}}</h6>
                         </div>
                       </div>
                     </td>

                     <td>
                       <div class="d-flex px-2 py-1">
                         <div class="d-flex flex-column justify-content-center">
                           <h6 class="mb-0 text-sm">{{vente.voiture}}</h6>
                         </div>
                       </div>
                     </td>


                     <td>
                       <div class="d-flex px-2 py-1">
                         <div class="d-flex flex-row justify-content-center">
                           <a class="btn btn-link text-dark btn-sm mb-0" href="{{url('afficher_vente',{'id':vente.id})}}"><i class="material-icons text-sm me-2">visibility</i>Afficher</a>
                           <a class="btn btn-link text-dark btn-sm mb-0" href="{{url('modifier_vente',{'id':vente.id})}}"><i class="material-icons text-sm me-2">edit</i>Modifier</a>
                           <a class="btn btn-link text-danger btn-sm mb-0" data-bs-toggle="modal" data-bs-target="#exampleModal"><i class="material-icons text-sm me-2">delete</i>Supprimer</a>
                           <!-- Modal -->
                           <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                             <div class="modal-dialog">
                               <div class="modal-content">
                                 <div class="modal-header">
                                   <h5 class="modal-title" id="exampleModalLabel">Suppression vente</h5>
                                   <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                 </div>
                                 <div class="modal-body">
                                   Etes vous sur de vouloir supprimer cet élément? </br>
                                   Cette action est irréversible!
                                 </div>
                                 <div class="modal-footer">
                                   <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                   <a href="{{url('supprimer_vente',{'id':vente.id})}}"><button type="button" class="btn btn-primary">Supprimer</button></a>
                                 </div>
                               </div>
                             </div>
                           </div>
                         </div>
                       </div>
                     </td>
             
                   </tr>
                   
                   {% endfor %}

                   {% endif %}

                   
                 </tbody>
               </table>
             </div>
           </div>
         </div>
       </div>
 </div>


{% endblock %}