src/Entity/Client.php
<?php

namespace App\Entity;

use App\Repository\ClientRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ClientRepository::class)
 */
class Client extends Personne
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $cni;

    /**
     * @ORM\OneToMany(targetEntity=Vente::class, mappedBy="client")
     */
    private $ventes;

    public function __construct()
    {
        $this->ventes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCni(): ?string
    {
        return $this->cni;
    }

    public function setCni(string $cni): self
    {
        $this->cni = $cni;

        return $this;
    }

    /**
     * @return Collection<int, Vente>
     */
    public function getVentes(): Collection
    {
        return $this->ventes;
    }

    public function addVente(Vente $vente): self
    {
        if (!$this->ventes->contains($vente)) {
            $this->ventes[] = $vente;
            $vente->setClient($this);
        }

        return $this;
    }

    public function removeVente(Vente $vente): self
    {
        if ($this->ventes->removeElement($vente)) {
            // set the owning side to null (unless already changed)
            if ($vente->getClient() === $this) {
                $vente->setClient(null);
            }
        }

        return $this;
    }
}

src/Entity/Personne.php
<?php

namespace App\Entity;

use App\Repository\PersonneRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\InheritanceType;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;


/**
 * @ORM\Entity(repositoryClass=PersonneRepository::class)
 */
class Personne implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    protected $nom;

    /**
     * @ORM\Column(type="string", length=100)
     */
    protected $prenom;

    /**
     * @ORM\Column(type="integer")
     */
    protected $telephone;

    /**
     * @ORM\Column(type="string", length=100)
     */
    protected $nom_utilisateur;

    /**
     * @ORM\Column(type="string", length=100)
     */
    protected $mot_de_passe;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getTelephone(): ?int
    {
        return $this->telephone;
    }

    public function setTelephone(int $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getNomUtilisateur(): ?string
    {
        return $this->nom_utilisateur;
    }

    public function setNomUtilisateur(string $nom_utilisateur): self
    {
        $this->nom_utilisateur = $nom_utilisateur;

        return $this;
    }

    public function getMotDePasse(): ?string
    {
        return $this->mot_de_passe;
    }

    public function setMotDePasse(string $mot_de_passe): self
    {
        $this->mot_de_passe = $mot_de_passe;

        return $this;
    }

    public function __toString() {
        return $this->nom;
    }

    private $email;

 

    /**
     * @var string The hashed password
     */
    private $password;

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->nom_utilisateur;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

src/Form/ClientType.php
<?php

namespace App\Form;

use App\Entity\Client;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ClientType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom',TextType::class , [ "attr" => ["class" => "form-control"] ])
            ->add('prenom',TextType::class , [ "attr" => ["class" => "form-control"] ])
            ->add('telephone',NumberType::class , [ "attr" => ["class" => "form-control"] ])
            ->add('nom_utilisateur',TextType::class , [ "attr" => ["class" => "form-control"] ])
            ->add('mot_de_passe',NumberType::class , [ "attr" => ["class" => "form-control"] ])
            ->add('cni',TextType::class , [ "attr" => ["class" => "form-control"] ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Client::class,
        ]);
    }
}

src/Controller/ClientController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Client;
use App\Form\ClientType;
use App\Repository\ClientRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

/**
 * @Route("/client")
 */
class ClientController extends AbstractController
{
    /**
     * @Route("/")
     */
    public function index(): Response
    {
        return $this->render('client/index.html.twig', [
            'controller_name' => 'ClientController',
        ]);
    }

    /**
     * @Route("/client/ajout_client", name="app_client_ajout")
     */
    public function ajout_client(Request $Request,clientRepository $clientRepository, UserPasswordHasherInterface $passwordhash, EntityManagerInterface $entityManager){
        $client = new Client();
        $form = $this->createForm(clientType::class, $client);
        $form -> handleRequest($Request); 
        $personne=$this->getUser();
        $username=$personne->getUserIdentifier;
        if($form->isSubmitted() && $form->isValid()){
            $hashPassword=$passwordhash->hashPassword($client, $client->getPassword());
            $entityManager -> persist($client);
            $entityManager -> flush();

            $this->denyAccessUnlessGranted('ROLE_CLIENT', null, "Erreur d'acces 404");
            $client->setRoles(["ROLE_CLIENT"]);

            $this->addFlash(
                'notice',
                "Un nouveau Client à été ajoutée !!");

            return $this->redirectToRoute('app_list_client');

        }
        return $this->renderForm('client/ajout_client.html.twig',[
            'client' => $client,
            'form' => $form,
        ]);
    }
    /**
     * @Route("/client/list_client", name="app_list_client")
     */
    public function list_client(ClientRepository $clientRepository) {
        $client = $clientRepository->findAll();
        return $this->render('client/list_client.html.twig', array(
            'clients' =>$client,
        ));
    }

    /**
     * @Route("/client/{id}/edit", name="app_modifier_client")
     */
    public function modifier_client(Request $request, Client $Client, EntityManagerInterface $entityManager ): Response
    {
        $form = $this->createForm(clientType::class, $Client);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $entityManager->flush();

            return $this->redirectToRoute('list_client');
        }
        return $this->render('client/modifier_client.html.twig', array(
            'form' => $form->createView(),
        ));
    }

    /**
     * @Route("/client/{id}", name="app_supprimer_client")
     */
    public function supprimer_client(Request $request, Client $client, EntityManagerInterface $entityManager): Response {
        $entityManager->flush();
        $entityManager -> remove($client);

        return $this->redirectToRoute('list_client');
    }

    /**
     * @Route("/client/{id}", name="app_afficher_client")
     */
    public function afficher_client(Client $client): Response
    {
        return $this->render('client/afficher_client.html.twig', [
            'client' => $client,
        ]);
    }

}

templates/client/_form.html.twig
{{form_start(form) }}
    <div class="input-group input-group-outline mb-3">
        <label class="form-label">Cni</label>
        {{form_widget (form.cni) }}
    </div>
    <div class="input-group input-group-outline mb-3">
        <label class="form-label">Nom</label>
        {{form_widget (form.nom) }}
    </div>
    <div class="input-group input-group-outline mb-3">
        <label class="form-label">Prenom</label>
            {{form_widget (form.prenom) }}
    </div>
        <div class="input-group input-group-outline mb-3">
        <label class="form-label">Telephone</label>
            {{form_widget (form.telephone) }}
    </div>
    <div class="input-group input-group-outline mb-3">
        <label class="form-label">nom utilisateur</label>
        {{form_widget (form.nom_utilisateur) }}
    </div>
    <div class="input-group input-group-outline mb-3">
        <label class="form-label">Mot de passe</label>
        {{form_widget (form.mot_de_passe) }}
    </div>
    
    
    <div class="text-center">
        <input type="submit" class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0" value="{{ button_label|default('Save') }}">
    </div>
{{ form_end(form)}}

templates/client/afficher_client.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {% block gestion_page %}Clients{% endblock %}
    {% block page_courante %}Afficher un Client{% endblock %}

    {% block contenu %}

        <div class="col-md-7 mt-4">
            <div>
                <a class="btn btn-outline-primary btn-sm mb-4" href="{{url('app_list_client')}}"><i class="material-icons text-sm me-2">keyboard_return</i>Retour</a>
            </div>
        
          <div class="card">
            <div class="card-header pb-0 px-3">
              <h3 class="mb-0">Informations Sur le Client:</h3>
            </div>
            <div class="card-body pt-4 p-3 mt-3">
                <div class="d-flex flex-column mr-4">
                    <h6 class="mb-3 text-lg">{{client.nom}} {{client.prenom}}</h6>
                    {% comment %} <span class="mb-2 text-sm">Date Naissancce: <span class="text-dark font-weight-bold ms-sm-2">{{client.dateNaissance.format('d/m/y')}}</span></span> {% endcomment %}
                    <span class="mb-2 text-sm">Telephone: <span class="text-dark font-weight-bold ms-sm-2">{{client.telephone}}</span></span>
                    <span class="mb-2 text-sm">Nom Utilisateur: <span class="text-dark ms-sm-2 font-weight-bold">{{client.nomUtilisateur}}</span></span>
                    <span class="text-sm">CNI: <span class="text-dark ms-sm-2 font-weight-bold">{{client.cni}}</span></span>
                    <span class="text-sm">Mot de Passe: <span class="text-dark ms-sm-2 font-weight-bold">{{client.motDePasse}}</span></span>
                </div>
            </div>
        </div>
{% endblock %}


{% comment %} <div class="col-12">
        
    <div class="card my-4">
    <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
        <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
        <h6 class="text-white text-capitalize ps-3">Clients</h6>
        <div class="col-6 text-end">
        </div>
    </div>
    
    <div class="card-body px-0 pb-2">
    <div class="ms-md-auto pe-md-3 d-flex align-items-center">
        <form action="{{path('Client')}}" method= "GET">
            <div class="input-group input-group-outline">
                <label class="form-label">Search here...</label>
                <input type="text" class="form-control" name="cni" >
            </div>
        </form>
    </div>
        <div class="table-responsive p-0">
        
        <a class="btn bg-gradient-dark mb-0" href="{{ path('app_client_ajout') }}"><i class="material-icons text-sm">add</i>&nbsp;&nbsp;Ajouter un Client</a>
        <table class="table align-items-center mb-0">
            <thead>
                <tr>
                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">id</th>
                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Cni</th>
                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Nom</th>
                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Prenom</th>
                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Telephone</th>
                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Nom de l'utilisateur</th>
                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Mot de passe</th>
                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Actions</th>
                    <th class="text-secondary opacity-7"></th>
                </tr>
            </thead>
            
            <tr>
                <td>
                    <div class="d-flex px-2 py-1">
                        {{ client.id }}    
                    </div>
                </td>

                <td>
                        {{ client.cni }} 
                </td>

                <td class="align-middle text-center text-sm">
                        {{ client.nom }} 
                </td>

                <td class="align-middle text-center">
                        {{ client.prenom }}
                </td>

                <td class="align-middle text-center">
                        {{ client.telephone }}
                </td>

                <td class="align-middle">
                        {{ client.nomUtilisateur }}
                </td>

                <td class="align-middle">
                        {{ client.motDePasse }} 
                </td>

                <td>
                    <div class="d-flex px-2 py-1">
                        <div class="ms-auto text-end">
                            <a class="btn btn-link text-dark px-3 mb-0" href="{{ path('app_modifier_client', {'id': client.id}) }}"><i class="material-icons text-sm me-2">edit</i>MODIFIER</a>
                            <a class="btn btn-link text-danger text-gradient px-3 mb-0" href="{{ path('app_supprimer_client', {'id': client.id}) }}"><i class="material-icons text-sm me-2">delete</i>SUPPRIMER</a>
                            
                        </div>
                    </div>
                </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
</div> {% endcomment %}

templates/client/ajout_client.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un client{% endblock %}

{% block body %}
{{ include('client/_form.html.twig') }}

    <a href="{{ path('app_list_client') }}">back to list</a>
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

    {% block contenu %}

        <breadcrumb>

        <div class="card-body">
            {{form_start(form) }}
            <div class="input-group input-group-outline mb-3">
                <label class="form-label">Cni</label>
                {{form_widget (form.cni, {'attr': {'class': 'form-control'}}) }}
            </div>
            <div class="input-group input-group-outline mb-3">
                <label class="form-label">Nom</label>
                {{form_widget (form.nom, {'attr': {'class': 'form-control'}}) }}
            </div>
            <div class="input-group input-group-outline mb-3">
                <label class="form-label">Prenom</label>
                    {{form_widget (form.prenom, {'attr': {'class': 'form-control'}}) }}
            </div>
                <div class="input-group input-group-outline mb-3">
                <label class="form-label">Telephone</label>
                    {{form_widget (form.telephone, {'attr': {'class': 'form-control'}}) }}
            </div>
            <div class="input-group input-group-outline mb-3">
                <label class="form-label">nom de l'utilisateur</label>
                {{form_widget (form.nom_utilisateur, {'attr': {'class': 'form-control'}}) }}
            </div>
            <div class="input-group input-group-outline mb-3">
                <label class="form-label">Mot de passe</label>
                {{form_widget (form.mot_de_passe, {'attr': {'class': 'form-control','type':'password'}}) }}
            </div>
                        
            <div class="text-center">
                <input type="submit" class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0" value="Enregistrer">
            </div>
            {{ form_end(form)}}
        </div>

    {% endblock %}
{% endblock %}

templates/client/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ClientController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/wamp64/it231/gestion_vente_voiture/src/Controller/ClientController.php'|file_link(0) }}">src/Controller/ClientController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/wamp64/it231/gestion_vente_voiture/templates/client/index.html.twig'|file_link(0) }}">templates/client/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/client/list_client.html.twig
{% extends 'base.html.twig' %}

    {% block gestion_page %}Clients{% endblock %}
    {% block page_courante %}Listes des Clients{% endblock %}

    {% block contenu %}
            <div class="row">
            <div class="col-12">
                <div class="card my-4">
                <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                    <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                    <h6 class="text-white text-capitalize ps-3">Clients</h6>
                    <div class="col-6 text-end">
                    </div>
                </div>
                
                <div class="card-body px-0 pb-2">
                <div class="ms-md-auto pe-md-3 d-flex align-items-center">
                    <form action="{{path('Client')}}" method= "GET">
                        <div class="input-group input-group-outline">
                            <label class="form-label">Search here...</label>
                            <input type="text" class="form-control" name="cni" >
                        </div>
                    </form>
                </div>
                <div class="table-responsive p-0">
                
                <a class="btn bg-gradient-dark mb-0" href="{{ path('app_client_ajout') }}"><i class="material-icons text-sm">add</i>&nbsp;&nbsp;Ajouter un Client</a>
                <table class="table align-items-center mb-0">
                    <thead>
                        <tr>
                            <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">#</th>
                            <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Cni</th>
                            <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Nom</th>
                            <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Prenom</th>
                            <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Telephone</th>
                            <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Nom de l'utilisateur</th>
                            <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Mot de passe</th>
                            <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Actions</th>
                            <th class="text-secondary opacity-7"></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% if clients == [] %}
                            <tr>
                                <td>
                                    <div class="d-flex px-2 py-1">
                                    <div class="d-flex flex-column justify-content-center">
                                        <h6 class="mb-0 text-sm">Pas encore de client, ajoutez en pour commencer.</h6>
                                    </div>
                                    </div>
                                </td>
                            <tr>
                        {% else %}
                        {% for client in clients %}
                        <tr>
                            <td>
                                <div class="d-flex px-2 py-1">
                                    {{ loop.index }}    
                                </div>
                            </td>

                            <td>
                                    {{ client.cni }} 
                            </td>

                            <td class="align-middle text-center text-sm">
                                    {{ client.nom }} 
                            </td>

                            <td class="align-middle text-center">
                                    {{ client.prenom }}
                            </td>

                            <td class="align-middle text-center">
                                    {{ client.telephone }}
                            </td>

                            <td class="align-middle">
                                    {{ client.nomUtilisateur }}
                            </td>

                            <td class="align-middle">
                                    {{ client.motDePasse }} 
                            </td>

                            {% if is_granted("ROLE_GERANT") %}

                            <td>
                                <div class="d-flex px-2 py-1">
                                    <div class="ms-auto text-end">
                                        <a class="btn btn-link text-dark px-3 mb-0" href=" {{ path('app_afficher_client', {'id': client.id}) }}"class="btn btn-secondary">AFFICHER</a>
                                        <a class="btn btn-link text-dark px-3 mb-0" href="{{ path('app_modifier_client', {'id': client.id}) }}"><i class="material-icons text-sm me-2">edit</i>MODIFIER</a>
                                        <a class="btn btn-link text-danger btn-sm mb-0" data-bs-toggle="modal" data-bs-target="#exampleModal"><i class="material-icons text-sm me-2">delete</i>Supprimer</a>
                                        <!-- Modal -->
                                        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="false">
                                            <div class="modal-dialog">
                                                <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">Suppression client</h5>
                                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                </div>
                                                <div class="modal-body">
                                                    Etes vous sur de vouloir supprimer cet élément? </br>
                                                    Cette action est irréversible!
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                                    <a href="{{url('app_supprimer_client',{'id':client.id })}}"><button type="button" class="btn btn-primary">Supprimer</button></a>
                                                </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        {% endfor %} 
                        {% endif %}                        
                    </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    {% endblock %} 

templates/client/modifier_client.html.twig
{% extends 'base.html.twig' %}

{% block titre %} Clients {% endblock %}

{% block gestion_page %}Clients {% endblock %}

{% block page_courante %}Modifier un client {% endblock %}

{% block body %}

    {{ include('client/_form.html.twig', {'button_label': 'Update'}) }}

    {% block contenu %}

        <breadcrumb>

            <div class="card-body">
                {{form_start(form) }}
                
                <label class="form-label">Cni</label>
                <div class="input-group input-group-outline mb-3">
                    {{form_widget (form.cni, {'attr': {'class': 'form-control'}}) }}
                </div>

                <label class="form-label">Nom</label>
                <div class="input-group input-group-outline mb-3">
                    {{form_widget (form.nom, {'attr': {'class': 'form-control'}}) }}
                </div>

               
                <label class="form-label">Prenom</label>
                <div class="input-group input-group-outline mb-3">
                    {{form_widget (form.prenom, {'attr': {'class': 'form-control'}}) }}
                </div>

                <label class="form-label">Telephone</label>
                <div class="input-group input-group-outline mb-3">
                    {{form_widget (form.telephone, {'attr': {'class': 'form-control'}}) }}
                </div>

                <label class="form-label">Nom utilisateur</label>
                <div class="input-group input-group-outline mb-3">   
                    {{form_widget (form.nom_utilisateur, {'attr': {'class': 'form-control'}}) }}
                </div>

                <label class="form-label">Mot de passe</label>
                <div class="input-group input-group-outline mb-3"> 
                    {{form_widget (form.mot_de_passe, {'attr': {'class': 'form-control'}}) }}
                </div>
                
                
                <div class="text-center">
                    <input type="submit" class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0" value="Enregistrer">
                </div>
                {{ form_end(form)}}
            </div>
            
        </div>
        </div>
        <footer class="footer position-absolute bottom-2 py-2 w-100">
            <div class="container">
            <div class="row align-items-center justify-content-lg-between">
                
            </div>
            </div>
        </footer>
        

    {% endblock %}

    {% endblock %}